---
- name: Update and upgrade apt packages
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "Installing dependencies"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
