---

- name: "update packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: add nodejs from the source
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt -y install nodejs

    sudo npm install --global n
    sudo n 13.8.0

 
- name: "Installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present