---
- name: Update and upgrade apt packages
  become: true
  apt:
    # upgrade: yes #no need to upgrade the existing system packages to reduce the build time
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "Add nodejs"
  become: true
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_13.x | bash -


- name: "Installing nodejs 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present