---
- name: "Fetch the artifact and extract it"
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: extract the backend files
  become: true
  shell: |
    cd /home/ubuntu
    tar xzf artifact.tar.gz -C .

- name: "Start the server"
  shell: | 
    # cd /home/ubuntu/
    # npm install
    pm2 stop default
    pm2 start npm -- start